"use client";

import React from "react";
import {
    Dialog,
    DialogTitle,
    DialogContent,
    TextField,
    Button,
    FormControl,
    InputLabel,
    Select,
    MenuItem,
    Menu,
    Box,
    Typography,
    CircularProgress,
    IconButton,
    Chip,
} from "@mui/material";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import MovieFilterIcon from "@mui/icons-material/MovieFilter";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import { formatTime } from "@/shared/utils/formatUtils";
import { useCreateSceneForm, getSceneMomentsCount, isRealtimeLibraryScene, getSceneDurationSeconds } from "@/features/content/content-builder/hooks";
import { ActivitySelector } from "./ActivitySelector";
import { BeatsEditor } from "./BeatsEditor";
import { MomentsEditor } from "./MomentsEditor";

interface CreateSceneDialogProps {
    open: boolean;
    onClose: () => void;
    onSceneCreated: (scene: any) => void;
    scenes?: any[];
    readOnly?: boolean;
    onSceneSelect?: (scene: any) => void;
    filmId?: number;
    packageId?: number | null;
    linkedActivityId?: number | null;
    instanceOwnerType?: "project" | "inquiry";
    instanceOwnerId?: number | null;
    onSceneDelete?: (scene: any) => void;
}

const CreateSceneDialog: React.FC<CreateSceneDialogProps> = ({
    open,
    onClose,
    onSceneCreated,
    scenes = [],
    readOnly = false,
    onSceneSelect,
    filmId,
    packageId,
    linkedActivityId,
    instanceOwnerType,
    instanceOwnerId,
    onSceneDelete,
}) => {
    const {
        formData,
        sceneMode, setSceneMode,
        includeGraphics, setIncludeGraphics,
        includeMusic, setIncludeMusic,
        moments,
        newMoment, setNewMoment,
        editingMomentId, setEditingMomentId,
        beats,
        newBeat, setNewBeat,
        editingBeatId, setEditingBeatId,
        loading,
        error,
        selectedLibraryId,
        sceneNameAnchorRef,
        libraryMenuOpen, setLibraryMenuOpen,
        selectedActivityIds, setSelectedActivityIds,
        scheduleDuration, setScheduleDuration,
        nameAutoGenerated,
        hasActivityContext,
        isMomentsScene,
        totalMomentsDuration,
        totalBeatsDuration,
        selectedActivities,
        groupedMoments,
        pkgActivities,
        pkgEventDays,
        activitiesLoading,
        handleInputChange,
        handleAddMoment,
        handleRemoveMoment,
        handleUpdateMoment,
        handleAddBeat,
        handleRemoveBeat,
        handleUpdateBeat,
        handleSelectLibraryScene,
        handleAddSceneToFilm,
    } = useCreateSceneForm({
        open,
        filmId,
        packageId,
        linkedActivityId,
        instanceOwnerType,
        instanceOwnerId,
        scenes,
        onSceneCreated,
        onSceneSelect,
        onClose,
    });

    return (
        <Dialog 
            open={open} 
            onClose={onClose}
            maxWidth="md"
            fullWidth
            PaperProps={{
                sx: {
                    bgcolor: "#141414",
                    backgroundImage: "none",
                    height: "78vh",
                    maxHeight: 700,
                    display: "flex",
                    flexDirection: "column",
                    borderRadius: 2,
                    border: '1px solid rgba(255,255,255,0.06)',
                }
            }}
        >
            <DialogTitle sx={{ color: "white", fontWeight: 500, fontSize: '1.1rem', pb: 1.5, pt: 2 }}>
                New Scene
            </DialogTitle>

            <DialogContent sx={{ 
                px: 3,
                pb: 3,
                pt: 0,
                display: "flex",
                flexDirection: "column",
                gap: 0,
                overflow: "auto",
                flex: 1,
                '&::-webkit-scrollbar': { width: 6 },
                '&::-webkit-scrollbar-track': { background: 'transparent' },
                '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 3, '&:hover': { background: 'rgba(255,255,255,0.14)' } },
                scrollbarWidth: 'thin',
                scrollbarColor: 'rgba(255,255,255,0.08) transparent',
            }}>
                {/* Create Form */}
                <Box sx={{ display: "flex", flexDirection: "column", gap: 0, flex: 1 }}>

                    <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
                        {/* Activity Selection */}
                        {hasActivityContext && (
                            <ActivitySelector
                                pkgActivities={pkgActivities}
                                pkgEventDays={pkgEventDays}
                                activitiesLoading={activitiesLoading}
                                selectedActivityIds={selectedActivityIds}
                                onToggle={(id) =>
                                    setSelectedActivityIds((prev) =>
                                        prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id],
                                    )
                                }
                            />
                        )}

                        {/* Scene Name */}
                        <Box ref={sceneNameAnchorRef}>
                            <TextField
                                label="Scene Name"
                                placeholder="Type a name or pick from library"
                                value={formData.name}
                                onChange={(e) => handleInputChange("name", e.target.value)}
                                fullWidth
                                required
                                autoFocus
                                InputProps={{
                                    endAdornment: (
                                        <IconButton
                                            size="small"
                                            onClick={() => setLibraryMenuOpen(true)}
                                            sx={{ color: "rgba(255,255,255,0.7)" }}
                                            aria-label="Select from library"
                                        >
                                            <ArrowDropDownIcon />
                                        </IconButton>
                                    ),
                                }}
                                sx={{
                                    "& .MuiOutlinedInput-root": {
                                        color: "white",
                                        "& fieldset": { borderColor: "rgba(255,255,255,0.1)" },
                                        "&:hover fieldset": { borderColor: "rgba(255,255,255,0.2)" },
                                        "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                    },
                                    "& .MuiInputBase-input::placeholder": {
                                        color: "rgba(255,255,255,0.25)",
                                        opacity: 1,
                                    },
                                    "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                }}
                            />
                            {nameAutoGenerated && (
                                <Typography sx={{ fontSize: 11, color: 'rgba(255,255,255,0.25)', mt: 0.5 }}>Auto-generated from activities</Typography>
                            )}
                        </Box>
                        <Menu
                            anchorEl={sceneNameAnchorRef.current}
                            open={libraryMenuOpen}
                            onClose={() => setLibraryMenuOpen(false)}
                            anchorOrigin={{ vertical: "bottom", horizontal: "left" }}
                            transformOrigin={{ vertical: "top", horizontal: "left" }}
                            disableAutoFocusItem
                            PaperProps={{
                                sx: {
                                    bgcolor: "#1a1a1a",
                                    border: "1px solid rgba(255,255,255,0.08)",
                                    maxHeight: 360,
                                    width: sceneNameAnchorRef.current?.clientWidth || 520,
                                    mt: 1,
                                    '&::-webkit-scrollbar': { width: 5 },
                                    '&::-webkit-scrollbar-track': { background: 'transparent' },
                                    '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 3, '&:hover': { background: 'rgba(255,255,255,0.14)' } },
                                    scrollbarWidth: 'thin',
                                    scrollbarColor: 'rgba(255,255,255,0.08) transparent',
                                },
                            }}
                        >
                            {scenes.map((scene) => {
                                const momentsCount = getSceneMomentsCount(scene);
                                const isRealtime = isRealtimeLibraryScene(scene);
                                const durationSeconds = getSceneDurationSeconds(scene);
                                const recordingSetup = scene.recording_setup || null;
                                const cameraCount = recordingSetup?.camera_count ?? 0;
                                const audioCount = recordingSetup?.audio_count ?? 0;
                                const graphicsEnabled = recordingSetup?.graphics_enabled === true;
                                return (
                                    <MenuItem
                                        key={scene.id}
                                        onClick={() => handleSelectLibraryScene(scene)}
                                        sx={{ alignItems: "flex-start", py: 1.25 }}
                                    >
                                        <Box sx={{ display: "flex", flexDirection: "column", gap: 0.75, width: "100%" }}>
                                            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                                                <Box sx={{
                                                    width: 22,
                                                    height: 22,
                                                    borderRadius: 0.75,
                                                    display: "flex",
                                                    alignItems: "center",
                                                    justifyContent: "center",
                                                    bgcolor: isRealtime ? "rgba(76,175,80,0.2)" : "rgba(255,176,32,0.2)",
                                                    color: isRealtime ? "#4CAF50" : "#FFB020",
                                                }}>
                                                    {isRealtime ? <AccessTimeIcon sx={{ fontSize: 14 }} /> : <MovieFilterIcon sx={{ fontSize: 14 }} />}
                                                </Box>
                                                <Typography sx={{ color: "white", fontSize: "0.9rem", fontWeight: 600 }}>
                                                    {scene.name}
                                                </Typography>
                                            </Box>
                                            <Box sx={{ display: "flex", alignItems: "center", gap: 1, flexWrap: "wrap" }}>
                                                <Typography sx={{ color: "rgba(255,255,255,0.65)", fontSize: "0.75rem" }}>
                                                    {formatTime(durationSeconds)}
                                                </Typography>
                                                <Chip
                                                    label={isRealtime ? "Realtime" : "Montage"}
                                                    size="small"
                                                    sx={{
                                                        fontSize: "0.6rem",
                                                        height: 18,
                                                        bgcolor: isRealtime ? "rgba(76,175,80,0.15)" : "rgba(255,176,32,0.15)",
                                                        color: isRealtime ? "#4CAF50" : "#FFB020",
                                                        border: `1px solid ${isRealtime ? "rgba(76,175,80,0.4)" : "rgba(255,176,32,0.4)"}`,
                                                        '& .MuiChip-label': { px: 0.75 },
                                                    }}
                                                />
                                                {momentsCount > 0 && (
                                                    <Chip
                                                        label={isRealtime ? `${momentsCount} Moments` : `${momentsCount} Beats`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(255, 255, 255, 0.15)",
                                                            color: "rgba(255, 255, 255, 0.9)",
                                                            border: "1px solid rgba(255, 255, 255, 0.2)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {cameraCount > 0 && (
                                                    <Chip
                                                        label={`${cameraCount} Cameras`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(76, 175, 80, 0.15)",
                                                            color: "rgba(76, 175, 80, 0.9)",
                                                            border: "1px solid rgba(76, 175, 80, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {audioCount > 0 && (
                                                    <Chip
                                                        label={`${audioCount} Audio`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(255, 107, 157, 0.15)",
                                                            color: "rgba(255, 107, 157, 0.9)",
                                                            border: "1px solid rgba(255, 107, 157, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {graphicsEnabled && (
                                                    <Chip
                                                        label="Graphics"
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(0, 229, 255, 0.15)",
                                                            color: "rgba(0, 229, 255, 0.9)",
                                                            border: "1px solid rgba(0, 229, 255, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                            </Box>
                                        </Box>
                                    </MenuItem>
                                );
                            })}
                        </Menu>

                        {/* Scene config row */}
                        <Box sx={{ display: 'flex', gap: 1.5, alignItems: 'flex-start' }}>
                            <FormControl size="small" sx={{ minWidth: 150 }}>
                                <InputLabel sx={{ color: "rgba(255,255,255,0.4)" }}>Type</InputLabel>
                                <Select
                                    value={sceneMode}
                                    onChange={(e) => setSceneMode(e.target.value as "MOMENTS" | "MONTAGE")}
                                    label="Type"
                                    sx={{
                                        color: "white",
                                        "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(255,255,255,0.1)" },
                                        "&:hover .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(255,255,255,0.2)" },
                                        "&.Mui-focused .MuiOutlinedInput-notchedOutline": { borderColor: "#7B61FF" },
                                        "& .MuiSvgIcon-root": { color: "rgba(255,255,255,0.4)" },
                                    }}
                                >
                                    <MenuItem value="MOMENTS">Realtime</MenuItem>
                                    <MenuItem value="MONTAGE">Montage</MenuItem>
                                </Select>
                            </FormControl>
                            <TextField
                                size="small"
                                label="Duration (min)"
                                type="number"
                                value={scheduleDuration}
                                onChange={(e) => setScheduleDuration(e.target.value)}
                                inputProps={{ min: 0 }}
                                InputLabelProps={{ sx: { color: "rgba(255,255,255,0.4)" } }}
                                sx={{ width: 120, input: { color: "white" }, '& fieldset': { borderColor: 'rgba(255,255,255,0.1)' }, '&:hover fieldset': { borderColor: 'rgba(255,255,255,0.2)' } }}
                            />
                            {/* Graphics + Music toggles inline */}
                            {isMomentsScene && (
                                <Box sx={{ display: 'flex', gap: 0.75, alignItems: 'center', ml: 'auto', pt: 0.5 }}>
                                    {[{ label: 'Graphics', value: includeGraphics, set: setIncludeGraphics }, { label: 'Music', value: includeMusic, set: setIncludeMusic }].map(({ label, value, set }) => (
                                        <Chip
                                            key={label}
                                            label={label}
                                            size="small"
                                            onClick={() => set(!value)}
                                            sx={{
                                                cursor: 'pointer',
                                                height: 26,
                                                fontSize: 11,
                                                fontWeight: value ? 500 : 400,
                                                bgcolor: value ? 'rgba(123,97,255,0.15)' : 'transparent',
                                                color: value ? '#a78bfa' : 'rgba(255,255,255,0.3)',
                                                border: `1px solid ${value ? 'rgba(123,97,255,0.35)' : 'rgba(255,255,255,0.08)'}`,
                                                '& .MuiChip-label': { px: 1 },
                                                '&:hover': { bgcolor: value ? 'rgba(123,97,255,0.22)' : 'rgba(255,255,255,0.05)' },
                                                transition: 'all 0.15s ease',
                                            }}
                                        />
                                    ))}
                                </Box>
                            )}
                        </Box>

                        {!isMomentsScene && (
                            <BeatsEditor
                                beats={beats}
                                newBeat={newBeat}
                                editingBeatId={editingBeatId}
                                totalDuration={totalBeatsDuration}
                                onNewBeatChange={setNewBeat}
                                onAddBeat={handleAddBeat}
                                onRemoveBeat={handleRemoveBeat}
                                onUpdateBeat={handleUpdateBeat}
                                onEditingIdChange={setEditingBeatId}
                            />
                        )}
                        {/* Moments Editor */}
                        {isMomentsScene && (
                            <MomentsEditor
                                groupedMoments={groupedMoments}
                                totalDuration={totalMomentsDuration}
                                momentCount={moments.length}
                                selectedActivitiesCount={selectedActivities.length}
                                newMoment={newMoment}
                                editingMomentId={editingMomentId}
                                onNewMomentChange={setNewMoment}
                                onAddMoment={handleAddMoment}
                                onRemoveMoment={handleRemoveMoment}
                                onUpdateMoment={handleUpdateMoment}
                                onEditingIdChange={setEditingMomentId}
                            />
                        )}

                        {/* Error Message */}
                        {error && (
                            <Typography
                                sx={{
                                    color: "#ff6b6b",
                                    fontSize: "0.875rem",
                                    p: 1,
                                    bgcolor: "rgba(255, 107, 107, 0.1)",
                                    borderRadius: 1,
                                }}
                            >
                                {error}
                            </Typography>
                        )}
                    </Box>

                    <Box sx={{ mt: "auto", pt: 2, display: "flex", gap: 1.5, justifyContent: "flex-end", borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                        <Button
                            onClick={onClose}
                            disabled={loading}
                            size="small"
                            sx={{ color: "rgba(255,255,255,0.4)", fontSize: 13 }}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleAddSceneToFilm}
                            disabled={loading}
                            variant="contained"
                            size="small"
                            sx={{
                                bgcolor: "#7B61FF",
                                color: "white",
                                px: 3,
                                fontSize: 13,
                                textTransform: 'none',
                                fontWeight: 500,
                                "&:hover": { bgcolor: "#6b4dd9" },
                                "&:disabled": { bgcolor: "rgba(123,97,255,0.5)" },
                            }}
                        >
                            {loading ? <CircularProgress size={18} /> : "Add Scene"}
                        </Button>
                    </Box>
                </Box>
            </DialogContent>
        </Dialog>
    );
};
export default CreateSceneDialog;
