databases:
  - name: projectflo-db
    plan: free
    databaseName: projectflo_db
    region: oregon

services:
  - type: web
    name: ProjectFlo
    runtime: node
    plan: free
    region: oregon
    branch: master
    rootDir: packages/backend
    buildCommand: corepack enable && corepack prepare pnpm@8 --activate && cd ../.. && NODE_ENV=development pnpm install --frozen-lockfile && cd packages/backend && NODE_ENV=production pnpm run build && NODE_ENV=production pnpm exec prisma migrate deploy && pnpm exec prisma db seed
    startCommand: node dist/src/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: projectflo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
