/**
 * Seed FloorPlanPreset records with pre-populated objects for common wedding space types.
 * These presets provide the default furniture layout that the AI blocking pipeline uses
 * as spatial context. Cameras and subjects are NOT seeded here — they are created
 * dynamically by syncCamerasAndSubjects() from crew/subject assignments.
 * Zones are NOT seeded here — they are generated by Gemma AI from the object layout
 * via generateZonesFromObjects() on first spatial context build.
 *
 * Run order: After service scaffolding so seeded package sets and floor plan presets are available together.
 */
import { PrismaClient, FloorPlanObjectType, SpaceType } from '@prisma/client';
import { createSeedLogger, SeedType, type SeedSummary } from '../utils/seed-logger';

const prisma = new PrismaClient();
const logger = createSeedLogger(SeedType.MOONRISE);

// ── Canvas dimensions (all presets use 1000×1000 normalised canvas) ──
const W = 1000;
const H = 1000;

// ── Type aliases for readability ──
type ObjDef = {
  object_type: FloorPlanObjectType;
  label: string;
  x: number; y: number;
  width: number; height: number;
  rotation?: number;
  order_index: number;
};

interface PresetDef {
  name: string;
  description: string;
  space_type: SpaceType;
  guest_capacity: number | null;
  objects: ObjDef[];
}

// ══════════════════════════════════════════════════════════════════════════════
// PRESET DEFINITIONS
// ══════════════════════════════════════════════════════════════════════════════

const CEREMONY_AREA: PresetDef = {
  name: 'Ceremony (100 guests)',
  description: 'Traditional ceremony layout with altar, aisle, and seating rows for ~100 guests',
  space_type: 'CEREMONY_AREA',
  guest_capacity: 100,
  objects: [
    { object_type: 'STAGE', label: 'Altar Platform', x: 380, y: 30, width: 240, height: 90, order_index: 0 },
    { object_type: 'ALTAR', label: 'Altar', x: 460, y: 50, width: 80, height: 40, order_index: 1 },
    { object_type: 'ARCH', label: 'Archway', x: 450, y: 15, width: 100, height: 30, order_index: 2 },
    { object_type: 'AISLE', label: 'Aisle', x: 460, y: 160, width: 80, height: 500, order_index: 3 },
    // Left seating (bride side) — 6 rows
    { object_type: 'CHAIR_ROW', label: 'Row 1L', x: 80, y: 180, width: 340, height: 30, order_index: 10 },
    { object_type: 'CHAIR_ROW', label: 'Row 2L', x: 80, y: 250, width: 340, height: 30, order_index: 11 },
    { object_type: 'CHAIR_ROW', label: 'Row 3L', x: 80, y: 320, width: 340, height: 30, order_index: 12 },
    { object_type: 'CHAIR_ROW', label: 'Row 4L', x: 80, y: 390, width: 340, height: 30, order_index: 13 },
    { object_type: 'CHAIR_ROW', label: 'Row 5L', x: 80, y: 460, width: 340, height: 30, order_index: 14 },
    { object_type: 'CHAIR_ROW', label: 'Row 6L', x: 80, y: 530, width: 340, height: 30, order_index: 15 },
    // Right seating (groom side) — 6 rows
    { object_type: 'CHAIR_ROW', label: 'Row 1R', x: 580, y: 180, width: 340, height: 30, order_index: 20 },
    { object_type: 'CHAIR_ROW', label: 'Row 2R', x: 580, y: 250, width: 340, height: 30, order_index: 21 },
    { object_type: 'CHAIR_ROW', label: 'Row 3R', x: 580, y: 320, width: 340, height: 30, order_index: 22 },
    { object_type: 'CHAIR_ROW', label: 'Row 4R', x: 580, y: 390, width: 340, height: 30, order_index: 23 },
    { object_type: 'CHAIR_ROW', label: 'Row 5R', x: 580, y: 460, width: 340, height: 30, order_index: 24 },
    { object_type: 'CHAIR_ROW', label: 'Row 6R', x: 580, y: 530, width: 340, height: 30, order_index: 25 },
  ],
};

const RECEPTION_HALL: PresetDef = {
  name: 'Reception Hall (150 guests)',
  description: 'Grand ballroom reception with head table, round guest tables, dance floor, and entertainment area',
  space_type: 'RECEPTION_HALL',
  guest_capacity: 150,
  objects: [
    { object_type: 'TABLE_HEAD', label: 'Head Table', x: 300, y: 40, width: 400, height: 60, order_index: 0 },
    { object_type: 'DANCE_FLOOR', label: 'Dance Floor', x: 350, y: 350, width: 300, height: 250, order_index: 1 },
    { object_type: 'TABLE_ROUND', label: 'Table 1', x: 100, y: 180, width: 100, height: 100, order_index: 10 },
    { object_type: 'TABLE_ROUND', label: 'Table 2', x: 100, y: 360, width: 100, height: 100, order_index: 11 },
    { object_type: 'TABLE_ROUND', label: 'Table 3', x: 100, y: 540, width: 100, height: 100, order_index: 12 },
    { object_type: 'TABLE_ROUND', label: 'Table 4', x: 800, y: 180, width: 100, height: 100, order_index: 13 },
    { object_type: 'TABLE_ROUND', label: 'Table 5', x: 800, y: 360, width: 100, height: 100, order_index: 14 },
    { object_type: 'TABLE_ROUND', label: 'Table 6', x: 800, y: 540, width: 100, height: 100, order_index: 15 },
    { object_type: 'TABLE_ROUND', label: 'Table 7', x: 300, y: 700, width: 100, height: 100, order_index: 16 },
    { object_type: 'TABLE_ROUND', label: 'Table 8', x: 600, y: 700, width: 100, height: 100, order_index: 17 },
    { object_type: 'DJ_BOOTH', label: 'DJ Booth', x: 420, y: 150, width: 160, height: 60, order_index: 20 },
    { object_type: 'BAR', label: 'Bar', x: 800, y: 800, width: 160, height: 60, order_index: 21 },
    { object_type: 'STAGE', label: 'Stage', x: 350, y: 120, width: 300, height: 50, order_index: 22 },
  ],
};

const BRIDAL_SUITE: PresetDef = {
  name: 'Bridal Suite',
  description: 'Elegant getting-ready room with mirror, dressing table, and seating area',
  space_type: 'BRIDAL_SUITE',
  guest_capacity: null,
  objects: [
    { object_type: 'FURNITURE', label: 'Full-Length Mirror', x: 450, y: 50, width: 100, height: 30, order_index: 0 },
    { object_type: 'FURNITURE', label: 'Dressing Table', x: 200, y: 50, width: 160, height: 60, order_index: 1 },
    { object_type: 'FURNITURE', label: 'Vanity Chair', x: 250, y: 130, width: 60, height: 60, order_index: 2 },
    { object_type: 'FURNITURE', label: 'Sofa', x: 650, y: 400, width: 200, height: 80, order_index: 3 },
    { object_type: 'FURNITURE', label: 'Armchair', x: 100, y: 400, width: 80, height: 80, order_index: 4 },
    { object_type: 'WINDOW', label: 'Bay Window', x: 350, y: 0, width: 300, height: 20, order_index: 5 },
    { object_type: 'DOOR', label: 'Entry Door', x: 0, y: 700, width: 20, height: 80, order_index: 6 },
    { object_type: 'FURNITURE', label: 'Dress Hanging Rail', x: 800, y: 100, width: 120, height: 30, order_index: 7 },
    { object_type: 'TABLE_RECT', label: 'Side Table', x: 750, y: 300, width: 80, height: 60, order_index: 8 },
  ],
};

const GROOM_SUITE: PresetDef = {
  name: 'Groom Suite',
  description: 'Smart getting-ready room with mirror, wardrobe area, and casual seating',
  space_type: 'GROOM_SUITE',
  guest_capacity: null,
  objects: [
    { object_type: 'FURNITURE', label: 'Full-Length Mirror', x: 450, y: 50, width: 100, height: 30, order_index: 0 },
    { object_type: 'FURNITURE', label: 'Wardrobe', x: 800, y: 50, width: 120, height: 60, order_index: 1 },
    { object_type: 'FURNITURE', label: 'Side Table', x: 200, y: 50, width: 100, height: 60, order_index: 2 },
    { object_type: 'FURNITURE', label: 'Armchair 1', x: 150, y: 400, width: 80, height: 80, order_index: 3 },
    { object_type: 'FURNITURE', label: 'Armchair 2', x: 700, y: 400, width: 80, height: 80, order_index: 4 },
    { object_type: 'WINDOW', label: 'Window', x: 350, y: 0, width: 300, height: 20, order_index: 5 },
    { object_type: 'DOOR', label: 'Entry Door', x: 0, y: 700, width: 20, height: 80, order_index: 6 },
  ],
};

const COCKTAIL_AREA: PresetDef = {
  name: 'Cocktail Hour Area',
  description: 'Open cocktail hour space with bar, high tables, and lounge seating',
  space_type: 'COCKTAIL_AREA',
  guest_capacity: 80,
  objects: [
    { object_type: 'BAR', label: 'Cocktail Bar', x: 400, y: 50, width: 200, height: 60, order_index: 0 },
    { object_type: 'TABLE_ROUND', label: 'High Table 1', x: 150, y: 300, width: 70, height: 70, order_index: 1 },
    { object_type: 'TABLE_ROUND', label: 'High Table 2', x: 400, y: 350, width: 70, height: 70, order_index: 2 },
    { object_type: 'TABLE_ROUND', label: 'High Table 3', x: 650, y: 300, width: 70, height: 70, order_index: 3 },
    { object_type: 'TABLE_ROUND', label: 'High Table 4', x: 850, y: 350, width: 70, height: 70, order_index: 4 },
    { object_type: 'FURNITURE', label: 'Lounge Seating', x: 100, y: 650, width: 250, height: 120, order_index: 5 },
    { object_type: 'FURNITURE', label: 'Lounge Seating 2', x: 650, y: 650, width: 250, height: 120, order_index: 6 },
  ],
};

const GARDEN: PresetDef = {
  name: 'Garden / Photo Area',
  description: 'Outdoor garden area with paths, archway, bench, and natural features for portraits',
  space_type: 'GARDEN',
  guest_capacity: null,
  objects: [
    { object_type: 'ARCH', label: 'Garden Archway', x: 420, y: 200, width: 160, height: 60, order_index: 0 },
    { object_type: 'FURNITURE', label: 'Stone Bench', x: 200, y: 500, width: 150, height: 50, order_index: 1 },
    { object_type: 'LABEL', label: 'Stone Path', x: 440, y: 400, width: 120, height: 400, order_index: 2 },
    { object_type: 'DECORATIVE', label: 'Fountain', x: 700, y: 350, width: 120, height: 120, order_index: 3 },
    { object_type: 'DECORATIVE', label: 'Rose Garden', x: 100, y: 200, width: 200, height: 150, order_index: 4 },
    { object_type: 'LABEL', label: 'Tree Line', x: 0, y: 0, width: 1000, height: 80, order_index: 5 },
  ],
};

const DANCE_FLOOR: PresetDef = {
  name: 'Dance Floor / Evening',
  description: 'Dance floor area with DJ booth, lighting rig, and surrounding seating',
  space_type: 'DANCE_FLOOR',
  guest_capacity: 120,
  objects: [
    { object_type: 'DANCE_FLOOR', label: 'Dance Floor', x: 300, y: 250, width: 400, height: 400, order_index: 0 },
    { object_type: 'DJ_BOOTH', label: 'DJ Booth', x: 400, y: 50, width: 200, height: 80, order_index: 1 },
    { object_type: 'BAR', label: 'Bar', x: 800, y: 300, width: 60, height: 200, order_index: 2 },
    { object_type: 'FURNITURE', label: 'Seating Area Left', x: 50, y: 350, width: 180, height: 200, order_index: 3 },
    { object_type: 'FURNITURE', label: 'Seating Area Right', x: 770, y: 700, width: 180, height: 200, order_index: 4 },
    { object_type: 'STAGE', label: 'Band/DJ Stage', x: 350, y: 50, width: 300, height: 100, order_index: 5 },
  ],
};

const CHAPEL: PresetDef = {
  name: 'Chapel / Mandap Area',
  description: 'Ornate ceremony space with mandap/altar structure, seating, and procession path',
  space_type: 'CHAPEL',
  guest_capacity: 120,
  objects: [
    { object_type: 'STAGE', label: 'Mandap / Altar Platform', x: 350, y: 30, width: 300, height: 150, order_index: 0 },
    { object_type: 'ALTAR', label: 'Sacred Fire / Altar', x: 440, y: 80, width: 120, height: 60, order_index: 1 },
    { object_type: 'ARCH', label: 'Mandap Canopy', x: 380, y: 20, width: 240, height: 170, order_index: 2 },
    { object_type: 'AISLE', label: 'Processional Path', x: 450, y: 200, width: 100, height: 500, order_index: 3 },
    { object_type: 'CHAIR_ROW', label: 'Row 1L', x: 80, y: 220, width: 340, height: 30, order_index: 10 },
    { object_type: 'CHAIR_ROW', label: 'Row 2L', x: 80, y: 300, width: 340, height: 30, order_index: 11 },
    { object_type: 'CHAIR_ROW', label: 'Row 3L', x: 80, y: 380, width: 340, height: 30, order_index: 12 },
    { object_type: 'CHAIR_ROW', label: 'Row 4L', x: 80, y: 460, width: 340, height: 30, order_index: 13 },
    { object_type: 'CHAIR_ROW', label: 'Row 1R', x: 580, y: 220, width: 340, height: 30, order_index: 20 },
    { object_type: 'CHAIR_ROW', label: 'Row 2R', x: 580, y: 300, width: 340, height: 30, order_index: 21 },
    { object_type: 'CHAIR_ROW', label: 'Row 3R', x: 580, y: 380, width: 340, height: 30, order_index: 22 },
    { object_type: 'CHAIR_ROW', label: 'Row 4R', x: 580, y: 460, width: 340, height: 30, order_index: 23 },
  ],
};

// ── All preset definitions ──
const ALL_PRESETS: PresetDef[] = [
  CEREMONY_AREA,
  RECEPTION_HALL,
  BRIDAL_SUITE,
  GROOM_SUITE,
  COCKTAIL_AREA,
  GARDEN,
  DANCE_FLOOR,
  CHAPEL,
];

// ══════════════════════════════════════════════════════════════════════════════
// SEED FUNCTION
// ══════════════════════════════════════════════════════════════════════════════

export default async function seedFloorPlanPresets(): Promise<SeedSummary> {
  logger.sectionHeader('Floor Plan Presets');

  let created = 0;
  let skipped = 0;

  for (const def of ALL_PRESETS) {
    const existing = await prisma.floorPlanPreset.findFirst({
      where: { brand_id: null, name: def.name },
    });
    if (existing) {
      skipped++;
      logger.skipped(def.name);
      continue;
    }

    await prisma.floorPlanPreset.create({
      data: {
        brand_id: null,
        name: def.name,
        description: def.description,
        space_type: def.space_type,
        guest_capacity: def.guest_capacity,
        canvas_width: W,
        canvas_height: H,
        is_system_seeded: true,
        objects: {
          create: def.objects.map((o) => ({
            object_type: o.object_type,
            label: o.label,
            x: o.x,
            y: o.y,
            width: o.width,
            height: o.height,
            rotation: o.rotation ?? 0,
            order_index: o.order_index,
          })),
        },
      },
    });

    logger.created(`${def.name} (${def.objects.length} objects)`);
    created++;
  }

  return { created, updated: 0, skipped, total: ALL_PRESETS.length };
}
