import { Injectable, Inject, NotFoundException, forwardRef } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { InquiryTasksService } from '../inquiry-tasks/inquiry-tasks.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { UpdateInvoiceDto } from './dto/update-invoice.dto';

@Injectable()
export class InvoicesService {
  constructor(
    private prisma: PrismaService,
    @Inject(forwardRef(() => InquiryTasksService))
    private inquiryTasksService: InquiryTasksService,
  ) { }

  async create(inquiryId: number, createInvoiceDto: CreateInvoiceDto) {
    // Calculate total amount from items
    const totalAmount = createInvoiceDto.items.reduce(
      (sum, item) => sum + (item.quantity * item.unit_price),
      0
    );

    return await this.prisma.$transaction(async (tx) => {
      // Create the invoice
      const invoice = await tx.invoices.create({
        data: {
          inquiry_id: inquiryId,
          project_id: createInvoiceDto.project_id || null,
          invoice_number: createInvoiceDto.invoice_number,
          issue_date: new Date(createInvoiceDto.issue_date),
          due_date: new Date(createInvoiceDto.due_date),
          amount: totalAmount,
          status: createInvoiceDto.status || 'Draft',
        },
      });

      // Create invoice items
      await Promise.all(
        createInvoiceDto.items.map(item =>
          tx.invoice_items.create({
            data: {
              invoice_id: invoice.id,
              description: item.description,
              quantity: item.quantity,
              unit_price: item.unit_price,
            },
          })
        )
      );

      return invoice;
    });
  }

  async findAll(inquiryId: number) {
    return await this.prisma.invoices.findMany({
      where: { inquiry_id: inquiryId },
      include: {
        items: true,
      },
      orderBy: { id: 'desc' },
    });
  }

  async findOne(inquiryId: number, id: number) {
    const invoice = await this.prisma.invoices.findFirst({
      where: {
        id: id,
        inquiry_id: inquiryId,
      },
      include: {
        items: true,
      },
    });

    if (!invoice) {
      throw new NotFoundException(`Invoice with ID ${id} not found for inquiry ${inquiryId}`);
    }

    return invoice;
  }

  async update(inquiryId: number, id: number, updateInvoiceDto: UpdateInvoiceDto) {
    // First verify the invoice exists and belongs to the inquiry
    await this.findOne(inquiryId, id);

    return await this.prisma.$transaction(async (tx) => {
      let totalAmount: number | undefined;

      // If items are being updated, calculate new total
      if (updateInvoiceDto.items) {
        totalAmount = updateInvoiceDto.items.reduce(
          (sum, item) => sum + ((item.quantity || 0) * (item.unit_price || 0)),
          0
        );

        // Delete existing items
        await tx.invoice_items.deleteMany({
          where: { invoice_id: id },
        });

        // Create new items
        await Promise.all(
          updateInvoiceDto.items.map(item =>
            tx.invoice_items.create({
              data: {
                invoice_id: id,
                description: item.description || '',
                quantity: item.quantity || 0,
                unit_price: item.unit_price || 0,
              },
            })
          )
        );
      }

      // Update the invoice
      const updateData = {
        ...(updateInvoiceDto.invoice_number && { invoice_number: updateInvoiceDto.invoice_number }),
        ...(updateInvoiceDto.issue_date && { issue_date: new Date(updateInvoiceDto.issue_date) }),
        ...(updateInvoiceDto.due_date && { due_date: new Date(updateInvoiceDto.due_date) }),
        ...(updateInvoiceDto.status && { status: updateInvoiceDto.status }),
        ...(updateInvoiceDto.project_id !== undefined && { project_id: updateInvoiceDto.project_id }),
        ...(totalAmount !== undefined && { amount: totalAmount }),
      };

      return await tx.invoices.update({
        where: { id },
        data: updateData,
        include: {
          items: true,
        },
      });
    });
  }

  async remove(inquiryId: number, id: number) {
    // First verify the invoice exists and belongs to the inquiry
    await this.findOne(inquiryId, id);

    return await this.prisma.invoices.delete({
      where: { id },
    });
  }

  async autoGenerateDepositInvoice(inquiryId: number): Promise<void> {
    const inquiry = await this.prisma.inquiries.findUnique({
      where: { id: inquiryId },
      select: {
        quotes: { select: { id: true, deposit_required: true, total_amount: true }, orderBy: { id: 'asc' }, take: 1 },
        selected_package: { select: { base_price: true } },
      },
    });

    const primaryQuote = inquiry?.quotes?.[0];
    const rawDeposit = primaryQuote?.deposit_required ?? primaryQuote?.total_amount ?? inquiry?.selected_package?.base_price ?? null;
    const depositAmount = rawDeposit != null ? Number(rawDeposit) : 0;

    const invoiceNumber = `DEP-${inquiryId}-${Date.now()}`;
    const now = new Date();
    const dueDate = new Date(now);
    dueDate.setDate(dueDate.getDate() + 7);

    const invoice = await this.prisma.invoices.create({
      data: {
        inquiry_id: inquiryId,
        invoice_number: invoiceNumber,
        issue_date: now,
        due_date: dueDate,
        amount: depositAmount,
        status: 'Sent',
      },
    });

    if (depositAmount > 0) {
      await this.prisma.invoice_items.create({
        data: {
          invoice_id: invoice.id,
          description: 'Booking Deposit',
          quantity: 1,
          unit_price: depositAmount,
        },
      });
    }

    await this.inquiryTasksService.autoCompleteByName(inquiryId, 'Raise Deposit Invoice');
  }
}
