/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState, useRef } from "react";
import { filmsApi } from "@/features/content/films/api";
import { momentsApi } from "@/features/content/moments/api";
import { beatsApi } from "@/features/content/beats/api";
import { scheduleApi } from "@/features/workflow/scheduling/api";
import { SceneType } from "@/features/content/scenes/types";
import { MediaType } from "@/features/content/content-builder/types/timeline";
import { usePackageActivities } from "./usePackageActivities";

export interface Moment {
    id?: string;
    name: string;
    duration: number;
    sourceType?: "activity" | "manual" | "library";
    sourceActivityId?: number;
    sourceActivityName?: string;
    sourceEventDayName?: string;
    sourceSceneName?: string;
}

export interface Beat {
    id?: string;
    name: string;
    duration_seconds: number;
    shot_count: number;
}

interface UseCreateSceneFormOptions {
    open: boolean;
    filmId?: number;
    packageId?: number | null;
    linkedActivityId?: number | null;
    instanceOwnerType?: "project" | "inquiry";
    instanceOwnerId?: number | null;
    scenes?: any[];
    onSceneCreated: (scene: any) => void;
    onSceneSelect?: (scene: any) => void;
    onClose: () => void;
}

const mapActivityMomentToDraft = (
    moment: any,
    activity: any,
    eventDayName: string | undefined,
    index: number,
): Moment => ({
    id: `activity-${activity.id}-${moment.id ?? index}`,
    name: moment.name,
    duration: moment.duration_seconds ?? moment.duration ?? 10,
    sourceType: "activity",
    sourceActivityId: activity.id,
    sourceActivityName: activity.name,
    sourceEventDayName: eventDayName,
});

export const getSceneMomentsCount = (scene: any) => scene.moments?.length || scene.moments_count || 0;

export const isRealtimeLibraryScene = (scene: any) => {
    const momentsCount = getSceneMomentsCount(scene);
    return scene.type === SceneType.MOMENTS ? true : scene.type === SceneType.MONTAGE ? false : momentsCount > 0;
};

export const getSceneDurationSeconds = (scene: any) =>
    (scene.moments || []).reduce((total: number, moment: any) => {
        const duration = moment.duration_seconds || moment.duration || moment.estimated_duration || 0;
        return total + duration;
    }, 0) || scene.estimated_duration || 0;

export function useCreateSceneForm({
    open,
    filmId,
    packageId,
    linkedActivityId,
    instanceOwnerType,
    instanceOwnerId,
    scenes = [],
    onSceneCreated,
    onSceneSelect,
    onClose,
}: UseCreateSceneFormOptions) {
    const [formData, setFormData] = useState({
        name: "",
        description: "",
        type: "VIDEO" as MediaType,
        estimated_duration: 30,
    });
    const [sceneMode, setSceneMode] = useState<"MOMENTS" | "MONTAGE">("MOMENTS");
    const [includeGraphics, setIncludeGraphics] = useState(false);
    const [includeMusic, setIncludeMusic] = useState(false);
    const [moments, setMoments] = useState<Moment[]>([]);
    const [newMoment, setNewMoment] = useState({ name: "", duration: 10 });
    const [editingMomentId, setEditingMomentId] = useState<string | null>(null);
    const [beats, setBeats] = useState<Beat[]>([]);
    const [newBeat, setNewBeat] = useState({ name: "", duration_seconds: 10, shot_count: 0 });
    const [editingBeatId, setEditingBeatId] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [selectedLibraryId, setSelectedLibraryId] = useState<number | null>(null);
    const sceneNameAnchorRef = useRef<HTMLDivElement>(null);
    const [libraryMenuOpen, setLibraryMenuOpen] = useState(false);
    const [selectedActivityIds, setSelectedActivityIds] = useState<number[]>([]);
    const [scheduleDuration, setScheduleDuration] = useState<string>("");
    const [nameAutoGenerated, setNameAutoGenerated] = useState(false);

    const hasActivityContext = Boolean(packageId || (instanceOwnerType && instanceOwnerId));
    const isInstanceOwner = Boolean(instanceOwnerType && instanceOwnerId);
    const isMomentsScene = sceneMode === "MOMENTS";

    const { pkgActivities, pkgEventDays, activitiesLoading } = usePackageActivities(
        open,
        packageId,
        instanceOwnerType,
        instanceOwnerId,
    );

    // Auto-select linked activity once activities load
    React.useEffect(() => {
        if (!open || !linkedActivityId || selectedActivityIds.length > 0 || pkgActivities.length === 0) return;
        if (pkgActivities.some((activity) => activity.id === linkedActivityId)) {
            setSelectedActivityIds([linkedActivityId]);
        }
    }, [open, linkedActivityId, pkgActivities, selectedActivityIds.length]);

    // Auto-name scene from selected activities
    React.useEffect(() => {
        if (selectedActivityIds.length === 0) return;
        const selected = pkgActivities.filter((a) => selectedActivityIds.includes(a.id));
        const generated = selected.map((a) => a.name).join(" & ");
        setFormData((prev) => ({ ...prev, name: generated }));
        setNameAutoGenerated(true);
        const totalMins = selected.reduce((sum, a) => sum + (a.duration_minutes ?? 0), 0);
        if (totalMins > 0) setScheduleDuration(String(totalMins));
    }, [selectedActivityIds, pkgActivities]);

    // Hydrate moments from selected activities
    React.useEffect(() => {
        if (!open) return;
        if (selectedActivityIds.length === 0) {
            setMoments((prev) => prev.filter((moment) => !moment.sourceActivityId));
            return;
        }
        const hydratedMoments = selectedActivityIds.flatMap((activityId) => {
            const activity = pkgActivities.find((a) => a.id === activityId);
            if (!activity) return [];
            const eventDayName = pkgEventDays.find(
                (day) => day._joinId === activity.package_event_day_id,
            )?.name;
            return (activity.moments ?? []).map((moment: any, index: number) =>
                mapActivityMomentToDraft(moment, activity, eventDayName, index),
            );
        });
        setMoments((prev) => {
            const manualMoments = prev.filter((m) => !m.sourceActivityId);
            return [...hydratedMoments, ...manualMoments];
        });
    }, [open, selectedActivityIds, pkgActivities, pkgEventDays]);

    const totalMomentsDuration = moments.reduce((sum, m) => sum + m.duration, 0);
    const totalBeatsDuration = beats.reduce((sum, b) => sum + b.duration_seconds, 0);

    const selectedActivities = React.useMemo(
        () =>
            selectedActivityIds
                .map((id) => pkgActivities.find((activity) => activity.id === id))
                .filter(Boolean),
        [selectedActivityIds, pkgActivities],
    );

    const groupedMoments = React.useMemo(() => {
        const groups: {
            key: string;
            groupType: string;
            title: string;
            subtitle: string;
            moments: Moment[];
            accent: string;
            accentBg: string;
            accentBorder: string;
        }[] = [];

        selectedActivities.forEach((activity: any) => {
            const eventDay = pkgEventDays.find((day) => day._joinId === activity.package_event_day_id);
            const activityMoments = moments.filter((m) => m.sourceActivityId === activity.id);
            groups.push({
                key: `activity-${activity.id}`,
                groupType: "activity",
                title: activity.name,
                subtitle: [
                    eventDay?.name,
                    activity.duration_minutes ? `${activity.duration_minutes} min` : null,
                ]
                    .filter(Boolean)
                    .join(" · "),
                moments: activityMoments,
                accent: "#c4b5fd",
                accentBg: "rgba(123,97,255,0.06)",
                accentBorder: "rgba(123,97,255,0.15)",
            });
        });

        const libraryMoments = moments.filter((m) => m.sourceType === "library");
        if (libraryMoments.length > 0) {
            const sceneName = libraryMoments[0].sourceSceneName || "Scene Template";
            groups.push({
                key: "library",
                groupType: "library",
                title: `From "${sceneName}"`,
                subtitle: "Scene template moments",
                moments: libraryMoments,
                accent: "#67e8f9",
                accentBg: "rgba(103,232,249,0.05)",
                accentBorder: "rgba(103,232,249,0.12)",
            });
        }

        const manualMoments = moments.filter((m) => !m.sourceActivityId && m.sourceType !== "library");
        if (manualMoments.length > 0 || groups.length === 0) {
            groups.push({
                key: "manual",
                groupType: "manual",
                title: "Custom Moments",
                subtitle: groups.length > 0 ? "Added manually" : "Add moments for this scene",
                moments: manualMoments,
                accent: "rgba(255,255,255,0.5)",
                accentBg: "rgba(255,255,255,0.02)",
                accentBorder: "rgba(255,255,255,0.06)",
            });
        }

        return groups;
    }, [moments, pkgEventDays, selectedActivities]);

    const handleInputChange = (field: string, value: any) => {
        setFormData((prev) => ({ ...prev, [field]: value }));
        if (field === "name") {
            if (selectedLibraryId !== null) setSelectedLibraryId(null);
            setNameAutoGenerated(false);
        }
        setError(null);
    };

    const handleAddMoment = () => {
        if (!newMoment.name.trim()) { setError("Moment name is required"); return; }
        if (newMoment.duration <= 0) { setError("Moment duration must be greater than 0"); return; }
        setMoments([...moments, { id: `temp-${Date.now()}`, name: newMoment.name.trim(), duration: newMoment.duration, sourceType: "manual" }]);
        setNewMoment({ name: "", duration: 10 });
        setError(null);
    };

    const handleRemoveMoment = (id?: string) => setMoments(moments.filter((m) => m.id !== id));

    const handleUpdateMoment = (id: string | undefined, updates: { name?: string; duration?: number }) => {
        setMoments(moments.map((m) => (m.id === id ? { ...m, ...updates } : m)));
        setEditingMomentId(null);
    };

    const handleAddBeat = () => {
        if (!newBeat.name.trim()) { setError("Beat name is required"); return; }
        if (newBeat.duration_seconds <= 0) { setError("Beat duration must be greater than 0"); return; }
        if (newBeat.shot_count < 0) { setError("Beat shot count must be 0 or more"); return; }
        setBeats([...beats, { id: `temp-${Date.now()}`, name: newBeat.name.trim(), duration_seconds: newBeat.duration_seconds, shot_count: newBeat.shot_count }]);
        setNewBeat({ name: "", duration_seconds: 10, shot_count: 0 });
        setError(null);
    };

    const handleRemoveBeat = (id?: string) => setBeats(beats.filter((b) => b.id !== id));

    const handleUpdateBeat = (id: string | undefined, updates: { name?: string; duration_seconds?: number; shot_count?: number }) => {
        setBeats(beats.map((b) => (b.id === id ? { ...b, ...updates } : b)));
        setEditingBeatId(null);
    };

    const resetForm = () => {
        setFormData({ name: "", description: "", type: "VIDEO", estimated_duration: 30 });
        setSceneMode("MOMENTS");
        setIncludeGraphics(false);
        setIncludeMusic(false);
        setMoments([]);
        setNewMoment({ name: "", duration: 10 });
        setEditingMomentId(null);
        setBeats([]);
        setNewBeat({ name: "", duration_seconds: 10, shot_count: 0 });
        setEditingBeatId(null);
        setSelectedActivityIds([]);
        setScheduleDuration("");
        setNameAutoGenerated(false);
    };

    const handleCreate = async () => {
        try {
            if (!formData.name.trim()) { setError("Scene name is required"); return; }
            if (isMomentsScene && moments.length === 0) { setError("Please add at least one moment"); return; }
            if (!isMomentsScene && beats.length === 0) { setError("Please add at least one beat"); return; }
            if (!filmId) { setError("Film ID is required to create a scene"); return; }

            setLoading(true);

            const sceneDuration = isMomentsScene ? totalMomentsDuration : totalBeatsDuration;
            const newScene = await filmsApi.localScenes.create(filmId, {
                name: formData.name,
                shot_count: null,
                duration_seconds: sceneDuration,
                mode: sceneMode,
            });

            const enhancedScene = {
                ...newScene,
                useMoments: isMomentsScene,
                scene_mode: sceneMode,
                scene_template_type: sceneMode,
                shot_count: null,
                duration: sceneDuration,
                estimated_duration: sceneDuration,
                includeGraphics,
                includeMusic,
                moments: isMomentsScene ? moments : [],
                beats: !isMomentsScene ? beats : [],
            };

            if (newScene.id && isMomentsScene) {
                localStorage.setItem(
                    `scene-moment-prefs-${newScene.id}`,
                    JSON.stringify({ useMoments: isMomentsScene, includeGraphics, includeMusic }),
                );
            }

            const createdMoments: any[] = [];
            if (isMomentsScene && newScene.id) {
                for (let i = 0; i < moments.length; i++) {
                    const moment = moments[i];
                    try {
                        createdMoments.push(
                            await momentsApi.create(newScene.id, { name: moment.name, duration: moment.duration, order_index: i }),
                        );
                    } catch (err) {
                        console.error(`Failed to create moment "${moment.name}":`, err);
                    }
                }
            }

            const createdBeats: any[] = [];
            if (!isMomentsScene && newScene.id) {
                for (let i = 0; i < beats.length; i++) {
                    const beat = beats[i];
                    try {
                        createdBeats.push(
                            await beatsApi.create(newScene.id, { name: beat.name, duration_seconds: beat.duration_seconds, order_index: i, shot_count: beat.shot_count }),
                        );
                    } catch (err) {
                        console.error(`Failed to create beat "${beat.name}":`, err);
                    }
                }
            }

            onSceneCreated({
                ...enhancedScene,
                moments: createdMoments.length > 0 ? createdMoments : enhancedScene.moments,
                beats: createdBeats.length > 0 ? createdBeats : enhancedScene.beats,
            });

            if (newScene.id && filmId && (selectedActivityIds.length > 0 || scheduleDuration)) {
                try {
                    const primaryActivity = pkgActivities.find((a) => a.id === selectedActivityIds[0]);
                    const upsertSceneSchedule =
                        instanceOwnerType === "project"
                            ? scheduleApi.projectFilms.upsertSceneSchedule
                            : instanceOwnerType === "inquiry"
                              ? scheduleApi.inquiryFilms.upsertSceneSchedule
                              : scheduleApi.film.upsertScene;
                    const eventDayId = primaryActivity
                        ? (pkgEventDays.find((d) => d._joinId === primaryActivity.package_event_day_id)?.id ?? null)
                        : null;
                    await upsertSceneSchedule(filmId, {
                        scene_id: newScene.id,
                        ...(isInstanceOwner
                            ? { project_activity_id: primaryActivity?.id ?? null, project_event_day_id: eventDayId }
                            : { event_day_template_id: eventDayId }),
                        scheduled_start_time: null,
                        scheduled_duration_minutes: scheduleDuration ? parseInt(scheduleDuration, 10) : null,
                    });
                } catch (schedErr) {
                    console.error("Failed to save scene schedule:", schedErr);
                }
            }

            resetForm();
            onClose();
        } catch (err: any) {
            setError(err.message || "Failed to create scene");
        } finally {
            setLoading(false);
        }
    };

    const handleSelectLibraryScene = (scene: any) => {
        setSelectedLibraryId(scene.id);
        setFormData((prev) => ({
            ...prev,
            name: scene.name || prev.name,
            estimated_duration: getSceneDurationSeconds(scene) || prev.estimated_duration,
        }));
        const realtime = isRealtimeLibraryScene(scene);
        setSceneMode(realtime ? "MOMENTS" : "MONTAGE");
        if (realtime) {
            setMoments(
                (scene.moments || []).map((moment: any) => ({
                    id: moment.id?.toString() || `template-${Date.now()}-${Math.random()}`,
                    name: moment.name,
                    duration: moment.duration_seconds || moment.duration || moment.estimated_duration || 10,
                    sourceType: "library" as const,
                    sourceSceneName: scene.name,
                })),
            );
            setBeats([]);
        } else {
            setBeats(
                (scene.moments || []).map((moment: any) => ({
                    id: moment.id?.toString() || `template-${Date.now()}-${Math.random()}`,
                    name: moment.name,
                    duration_seconds: moment.duration_seconds || moment.duration || moment.estimated_duration || 10,
                    shot_count: 0,
                })),
            );
            setMoments([]);
        }
        setLibraryMenuOpen(false);
    };

    const handleAddSceneToFilm = async () => {
        if (selectedLibraryId !== null) {
            const selected = scenes.find((scene) => scene.id === selectedLibraryId);
            if (selected && onSceneSelect) {
                onSceneSelect(selected);
                setSelectedLibraryId(null);
                onClose();
            }
            return;
        }
        await handleCreate();
    };

    return {
        // State
        formData, setFormData,
        sceneMode, setSceneMode,
        includeGraphics, setIncludeGraphics,
        includeMusic, setIncludeMusic,
        moments,
        newMoment, setNewMoment,
        editingMomentId, setEditingMomentId,
        beats,
        newBeat, setNewBeat,
        editingBeatId, setEditingBeatId,
        loading,
        error,
        selectedLibraryId,
        sceneNameAnchorRef,
        libraryMenuOpen, setLibraryMenuOpen,
        selectedActivityIds, setSelectedActivityIds,
        scheduleDuration, setScheduleDuration,
        nameAutoGenerated,
        // Derived
        hasActivityContext,
        isMomentsScene,
        totalMomentsDuration,
        totalBeatsDuration,
        selectedActivities,
        groupedMoments,
        // Activity data from hook
        pkgActivities,
        pkgEventDays,
        activitiesLoading,
        // Handlers
        handleInputChange,
        handleAddMoment,
        handleRemoveMoment,
        handleUpdateMoment,
        handleAddBeat,
        handleRemoveBeat,
        handleUpdateBeat,
        handleCreate,
        handleSelectLibraryScene,
        handleAddSceneToFilm,
    };
}
