export const DEFAULT_TEMPLATE_QUESTIONS = [
    { order_index: 1, prompt: 'Contact first name', field_type: 'text', field_key: 'contact_first_name', required: true, category: 'contact' },
    { order_index: 2, prompt: 'Contact last name', field_type: 'text', field_key: 'contact_last_name', required: true, category: 'contact' },
    { order_index: 3, prompt: 'Contact email', field_type: 'email', field_key: 'contact_email', required: true, category: 'contact' },
    { order_index: 4, prompt: 'Contact phone number', field_type: 'phone', field_key: 'contact_phone', required: false, category: 'contact' },
    { order_index: 5, prompt: 'Your role in the wedding', field_type: 'select', field_key: 'contact_role', required: false, options: { values: ['Bride', 'Groom', 'Partner', 'Prefer not to say'] }, help_text: 'This helps us personalise your experience.', category: 'contact' },
    { order_index: 6, prompt: "Your partner's name", field_type: 'text', field_key: 'partner_name', required: false, help_text: 'Leave blank if you prefer not to say or are still deciding.', category: 'contact' },
    { order_index: 7, prompt: 'Wedding / Event date', field_type: 'date', field_key: 'wedding_date', required: true, category: 'event' },
    { order_index: 8, prompt: 'Ceremony venue name', field_type: 'text', field_key: 'ceremony_location', required: false, help_text: 'Where is your ceremony being held? Leave blank if TBC.', category: 'event' },
    { order_index: 9, prompt: 'Bridal preparation venue', field_type: 'text', field_key: 'bridal_prep_location', required: false, help_text: 'e.g. hotel, home — leave blank if unknown.', category: 'event' },
    { order_index: 10, prompt: 'Groom / partner preparation venue', field_type: 'text', field_key: 'groom_prep_location', required: false, help_text: 'Leave blank if unknown or prefer not to say.', category: 'event' },
    { order_index: 11, prompt: 'Reception venue', field_type: 'text', field_key: 'reception_location', required: false, help_text: 'Leave blank if same as ceremony or TBC.', category: 'event' },
    { order_index: 12, prompt: 'Priority level', field_type: 'select', field_key: 'priority_level', required: true, options: { values: ['Low', 'Medium', 'High'] }, category: 'event' },
    { order_index: 13, prompt: 'Coverage hours needed', field_type: 'select', field_key: 'coverage_hours', required: false, options: { values: ['4-6 hours', '6-8 hours', '8-10 hours', 'Full day'] }, category: 'coverage' },
    { order_index: 14, prompt: 'Deliverables requested', field_type: 'multiselect', field_key: 'deliverables', required: false, options: { values: ['Highlight film', 'Full ceremony', 'Speeches', 'Raw footage', 'Social clips'] }, category: 'coverage' },
    { order_index: 15, prompt: 'Add-ons / extras', field_type: 'multiselect', field_key: 'add_ons', required: false, options: { values: ['Drone coverage', 'Second shooter', 'Same-day edit', 'Live stream'] }, category: 'coverage' },
    { order_index: 16, prompt: 'Budget range', field_type: 'select', field_key: 'budget_range', required: false, options: { values: ['£2k-£4k', '£4k-£6k', '£6k-£8k', '£8k+'] }, category: 'budget' },
    { order_index: 17, prompt: 'Budget flexibility', field_type: 'select', field_key: 'budget_flexible', required: false, options: { values: ['Fixed', 'Some flexibility', 'Flexible'] }, category: 'budget' },
    { order_index: 18, prompt: 'Decision timeline', field_type: 'select', field_key: 'decision_timeline', required: false, options: { values: ['ASAP', '1-2 weeks', '1 month', 'Just exploring'] }, category: 'reach' },
    { order_index: 19, prompt: 'Target booking date', field_type: 'date', field_key: 'booking_date', required: false, category: 'reach' },
    { order_index: 20, prompt: 'Key stakeholders / who decides', field_type: 'text', field_key: 'stakeholders', required: false, category: 'reach' },
    { order_index: 21, prompt: 'Preferred communication method', field_type: 'select', field_key: 'preferred_contact_method', required: false, options: { values: ['Email', 'Phone', 'Text', 'Zoom'] }, category: 'reach' },
    { order_index: 22, prompt: 'Preferred contact time', field_type: 'text', field_key: 'preferred_contact_time', required: false, category: 'reach' },
    { order_index: 23, prompt: 'Additional notes', field_type: 'textarea', field_key: 'notes', required: false, category: 'reach' },
];

export const DEFAULT_TEMPLATE_STEPS = [
    { key: 'contact', label: 'You', description: "Let's start with the basics" },
    { key: 'event', label: 'Your Wedding', description: 'Tell us about your day' },
    { key: 'coverage', label: 'Coverage', description: "What you'd like us to capture" },
    { key: 'budget', label: 'Budget', description: 'Help us find the right fit' },
    { key: 'package', label: 'Package', description: 'Choose your package', type: 'package_select' },
    { key: 'reach', label: 'Reach You', description: 'How best to connect' },
    { key: 'call', label: 'Discovery Call', description: 'How would you like to connect?', type: 'discovery_call' },
];
