"use client";

import React, { useState, useRef } from "react";
import {
    Dialog,
    DialogTitle,
    DialogContent,
    TextField,
    Button,
    FormControl,
    InputLabel,
    Select,
    MenuItem,
    Menu,
    Box,
    Typography,
    CircularProgress,
    IconButton,
    List,
    ListItem,
    ListItemText,
    Chip,
} from "@mui/material";
import DeleteIcon from "@mui/icons-material/Delete";
import EditIcon from "@mui/icons-material/Edit";
import CheckIcon from "@mui/icons-material/Check";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import MovieFilterIcon from "@mui/icons-material/MovieFilter";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import { MediaType } from "@/lib/types/timeline";
import { api } from "@/lib/api";
import { SceneType } from "@/lib/types/domains/scenes";
import { formatTime } from "@/lib/utils/formatUtils";

interface Moment {
    id?: string;
    name: string;
    duration: number;
}

interface Beat {
    id?: string;
    name: string;
    duration_seconds: number;
    shot_count: number;
}

interface CreateSceneDialogProps {
    open: boolean;
    onClose: () => void;
    onSceneCreated: (scene: any) => void;
    scenes?: any[];
    readOnly?: boolean;
    onSceneSelect?: (scene: any) => void;
    filmId?: number;
    packageId?: number | null;
    onSceneDelete?: (scene: any) => void;
}

const CreateSceneDialog: React.FC<CreateSceneDialogProps> = ({
    open,
    onClose,
    onSceneCreated,
    scenes = [],
    readOnly = false,
    onSceneSelect,
    filmId,
    packageId,
    onSceneDelete,
}) => {
    const [formData, setFormData] = useState({
        name: "",
        description: "",
        type: "VIDEO" as MediaType,
        estimated_duration: 30,
    });
    const [sceneMode, setSceneMode] = useState<"MOMENTS" | "MONTAGE">("MOMENTS");
    const [includeGraphics, setIncludeGraphics] = useState(false);
    const [includeMusic, setIncludeMusic] = useState(false);
    const [moments, setMoments] = useState<Moment[]>([]);
    const [newMoment, setNewMoment] = useState({ name: "", duration: 10 });
    const [editingMomentId, setEditingMomentId] = useState<string | null>(null);
    const [beats, setBeats] = useState<Beat[]>([]);
    const [newBeat, setNewBeat] = useState({ name: "", duration_seconds: 10, shot_count: 0 });
    const [editingBeatId, setEditingBeatId] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [selectedLibraryId, setSelectedLibraryId] = useState<number | null>(null);
    const sceneNameAnchorRef = useRef<HTMLDivElement>(null);
    const [libraryMenuOpen, setLibraryMenuOpen] = useState(false);

    // Activity & schedule state
    const [pkgActivities, setPkgActivities] = useState<any[]>([]);
    const [pkgEventDays, setPkgEventDays] = useState<any[]>([]);
    const [activitiesLoading, setActivitiesLoading] = useState(false);
    const [selectedActivityIds, setSelectedActivityIds] = useState<number[]>([]);
    const [scheduleDuration, setScheduleDuration] = useState<string>("");
    const [nameAutoGenerated, setNameAutoGenerated] = useState(false);

    // Load package activities when packageId provided
    React.useEffect(() => {
        if (!packageId) { setPkgActivities([]); setPkgEventDays([]); return; }
        setActivitiesLoading(true);
        Promise.all([
            api.schedule.packageActivities.getAll(packageId),
            api.schedule.packageEventDays.getAll(packageId),
        ]).then(([acts, days]) => {
            setPkgActivities(acts ?? []);
            setPkgEventDays(days ?? []);
        }).catch(console.error).finally(() => setActivitiesLoading(false));
    }, [packageId]);

    // Auto-generate scene name from selected activities
    React.useEffect(() => {
        if (selectedActivityIds.length === 0) return;
        const selected = pkgActivities.filter(a => selectedActivityIds.includes(a.id));
        const generated = selected.map(a => a.name).join(' & ');
        setFormData(prev => ({ ...prev, name: generated }));
        setNameAutoGenerated(true);
        const totalMins = selected.reduce((sum, a) => sum + (a.duration_minutes ?? 0), 0);
        if (totalMins > 0) setScheduleDuration(String(totalMins));
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [selectedActivityIds]);

    const isMomentsScene = sceneMode === "MOMENTS";

    const handleInputChange = (field: string, value: any) => {
        setFormData(prev => ({
            ...prev,
            [field]: value,
        }));
        if (field === "name") {
            if (selectedLibraryId !== null) setSelectedLibraryId(null);
            setNameAutoGenerated(false);
        }
        setError(null);
    };

    // Add a moment to the list
    const handleAddMoment = () => {
        if (!newMoment.name.trim()) {
            setError("Moment name is required");
            return;
        }
        if (newMoment.duration <= 0) {
            setError("Moment duration must be greater than 0");
            return;
        }

        const momentToAdd: Moment = {
            id: `temp-${Date.now()}`,
            name: newMoment.name.trim(),
            duration: newMoment.duration,
        };

        setMoments([...moments, momentToAdd]);
        setNewMoment({ name: "", duration: 10 });
        setError(null);
    };

    // Remove a moment
    const handleRemoveMoment = (id?: string) => {
        setMoments(moments.filter(m => m.id !== id));
    };

    // Update a moment (for editing)
    const handleUpdateMoment = (id: string | undefined, updates: { name?: string; duration?: number }) => {
        setMoments(moments.map(m => 
            m.id === id ? { ...m, ...updates } : m
        ));
        setEditingMomentId(null);
    };

    // Calculate total moments duration
    const totalMomentsDuration = moments.reduce((sum, m) => sum + m.duration, 0);
    const totalBeatsDuration = beats.reduce((sum, b) => sum + b.duration_seconds, 0);

    const handleAddBeat = () => {
        if (!newBeat.name.trim()) {
            setError("Beat name is required");
            return;
        }
        if (newBeat.duration_seconds <= 0) {
            setError("Beat duration must be greater than 0");
            return;
        }
        if (newBeat.shot_count < 0) {
            setError("Beat shot count must be 0 or more");
            return;
        }

        const beatToAdd: Beat = {
            id: `temp-${Date.now()}`,
            name: newBeat.name.trim(),
            duration_seconds: newBeat.duration_seconds,
            shot_count: newBeat.shot_count,
        };

        setBeats([...beats, beatToAdd]);
        setNewBeat({ name: "", duration_seconds: 10, shot_count: 0 });
        setError(null);
    };

    const handleRemoveBeat = (id?: string) => {
        setBeats(beats.filter(b => b.id !== id));
    };

    const handleUpdateBeat = (id: string | undefined, updates: { name?: string; duration_seconds?: number; shot_count?: number }) => {
        setBeats(beats.map(b =>
            b.id === id ? { ...b, ...updates } : b
        ));
        setEditingBeatId(null);
    };

    const handleCreate = async () => {
        try {
            // Validate required fields
            if (!formData.name.trim()) {
                setError("Scene name is required");
                return;
            }

            if (isMomentsScene && moments.length === 0) {
                setError("Please add at least one moment");
                return;
            }

            if (!isMomentsScene && beats.length === 0) {
                setError("Please add at least one beat");
                return;
            }

            setLoading(true);

            if (!filmId) {
                setError("Film ID is required to create a scene");
                return;
            }

            const sceneDuration = isMomentsScene ? totalMomentsDuration : totalBeatsDuration;

            // Create film scene via API
            const newScene = await api.films.localScenes.create(filmId, {
                name: formData.name,
                shot_count: null,
                duration_seconds: sceneDuration,
            });

            // Add moment preferences to scene object for later use in timeline
            const enhancedScene = {
                ...newScene,
                useMoments: isMomentsScene,
                scene_mode: sceneMode,
                scene_template_type: sceneMode,
                shot_count: null,
                duration: sceneDuration,
                estimated_duration: sceneDuration,
                includeGraphics,
                includeMusic,
            };

            // Store moment preferences in localStorage for persistence across reloads
            if (newScene.id && isMomentsScene) {
                const scenePrefs = {
                    useMoments: isMomentsScene,
                    includeGraphics,
                    includeMusic,
                };
                localStorage.setItem(`scene-moment-prefs-${newScene.id}`, JSON.stringify(scenePrefs));
            }

            // If using moments, create them
            let createdMoments: any[] = [];
            if (isMomentsScene && newScene.id) {
                console.log("📝 Creating moments for scene...");
                for (let i = 0; i < moments.length; i++) {
                    const moment = moments[i];
                    try {
                        const created = await api.moments.create(newScene.id, {
                            name: moment.name,
                            duration: moment.duration,
                            order_index: i,
                        });
                        createdMoments.push(created);
                        console.log(`✅ Moment "${moment.name}" created`);
                    } catch (err) {
                        console.error(`❌ Failed to create moment "${moment.name}":`, err);
                    }
                }
            }

            let createdBeats: any[] = [];
            if (!isMomentsScene && newScene.id) {
                console.log("📝 Creating beats for scene...");
                for (let i = 0; i < beats.length; i++) {
                    const beat = beats[i];
                    try {
                        const created = await api.beats.create(newScene.id, {
                            name: beat.name,
                            duration_seconds: beat.duration_seconds,
                            order_index: i,
                            shot_count: beat.shot_count,
                        });
                        createdBeats.push(created);
                        console.log(`✅ Beat "${beat.name}" created`);
                    } catch (err) {
                        console.error(`❌ Failed to create beat "${beat.name}":`, err);
                    }
                }
            }

            if (createdBeats.length > 0) {
                console.log("✅ Beats created for new scene:", createdBeats.map((beat) => ({
                    id: beat.id,
                    name: beat.name,
                    order_index: beat.order_index,
                    duration_seconds: beat.duration_seconds,
                    shot_count: beat.shot_count ?? null,
                })));
            }

            onSceneCreated({
                ...enhancedScene,
                moments: createdMoments.length > 0 ? createdMoments : enhancedScene.moments,
                beats: createdBeats.length > 0 ? createdBeats : enhancedScene.beats,
            });

            // Save schedule if activities or duration set
            if (newScene.id && filmId && (selectedActivityIds.length > 0 || scheduleDuration)) {
                try {
                    const primaryActivity = pkgActivities.find(a => a.id === selectedActivityIds[0]);
                    const eventDayTemplateId = primaryActivity
                        ? (pkgEventDays.find(d => d._joinId === primaryActivity.package_event_day_id)?.id ?? null)
                        : null;
                    await api.schedule.film.upsertScene(filmId, {
                        scene_id: newScene.id,
                        event_day_template_id: eventDayTemplateId,
                        scheduled_start_time: null,
                        scheduled_duration_minutes: scheduleDuration ? parseInt(scheduleDuration, 10) : null,
                    });
                    console.log("\u2705 Scene schedule saved");
                } catch (schedErr) {
                    console.error("Failed to save scene schedule:", schedErr);
                }
            }

            // Reset form
            setFormData({
                name: "",
                description: "",
                type: "VIDEO",
                estimated_duration: 30,
            });
            setSceneMode("MOMENTS");
            setIncludeGraphics(false);
            setIncludeMusic(false);
            setMoments([]);
            setNewMoment({ name: "", duration: 10 });
            setEditingMomentId(null);
            setBeats([]);
            setNewBeat({ name: "", duration_seconds: 10, shot_count: 0 });
            setEditingBeatId(null);
            setSelectedActivityIds([]);
            setScheduleDuration("");
            setNameAutoGenerated(false);
            onClose();
        } catch (err: any) {
            console.error("Failed to create scene:", err);
            setError(err.message || "Failed to create scene");
        } finally {
            setLoading(false);
        }
    };

    const getSceneMomentsCount = (scene: any) => scene.moments?.length || scene.moments_count || 0;
    const isRealtimeLibraryScene = (scene: any) => {
        const momentsCount = getSceneMomentsCount(scene);
        return scene.type === SceneType.MOMENTS ? true : scene.type === SceneType.MONTAGE ? false : momentsCount > 0;
    };

    const getSceneDurationSeconds = (scene: any) =>
        (scene.moments || []).reduce((total: number, moment: any) => {
            const duration = moment.duration_seconds || moment.duration || moment.estimated_duration || 0;
            return total + duration;
        }, 0) || scene.estimated_duration || 0;

    const handleSelectLibraryScene = (scene: any) => {
        setSelectedLibraryId(scene.id);
        setFormData(prev => ({
            ...prev,
            name: scene.name || prev.name,
            estimated_duration: scene.estimated_duration || prev.estimated_duration,
        }));
        const realtime = isRealtimeLibraryScene(scene);
        setSceneMode(realtime ? "MOMENTS" : "MONTAGE");
        if (realtime) {
            const templateMoments = (scene.moments || []).map((moment: any) => ({
                id: moment.id?.toString() || `template-${Date.now()}-${Math.random()}`,
                name: moment.name,
                duration: moment.duration_seconds || moment.duration || moment.estimated_duration || 10,
            }));
            setMoments(templateMoments);
            setBeats([]);
        } else {
            const templateBeats = (scene.moments || []).map((moment: any) => ({
                id: moment.id?.toString() || `template-${Date.now()}-${Math.random()}`,
                name: moment.name,
                duration_seconds: moment.duration_seconds || moment.duration || moment.estimated_duration || 10,
                shot_count: 0,
            }));
            setBeats(templateBeats);
            setMoments([]);
        }
        setLibraryMenuOpen(false);
    };

    const handleAddSceneToFilm = async () => {
        if (selectedLibraryId !== null) {
            const selected = scenes.find((scene) => scene.id === selectedLibraryId);
            if (selected && onSceneSelect) {
                onSceneSelect(selected);
                setSelectedLibraryId(null);
                onClose();
            }
            return;
        }
        await handleCreate();
    };

    return (
        <Dialog 
            open={open} 
            onClose={onClose}
            maxWidth="md"
            fullWidth
            PaperProps={{
                sx: {
                    bgcolor: "#141414",
                    backgroundImage: "none",
                    height: "78vh",
                    maxHeight: 700,
                    display: "flex",
                    flexDirection: "column",
                    borderRadius: 2,
                    border: '1px solid rgba(255,255,255,0.06)',
                }
            }}
        >
            <DialogTitle sx={{ color: "white", fontWeight: 500, fontSize: '1.1rem', pb: 1.5, pt: 2 }}>
                New Scene
            </DialogTitle>

            <DialogContent sx={{ 
                px: 3,
                pb: 3,
                pt: 0,
                display: "flex",
                flexDirection: "column",
                gap: 0,
                overflow: "auto",
                flex: 1,
                '&::-webkit-scrollbar': { width: 6 },
                '&::-webkit-scrollbar-track': { background: 'transparent' },
                '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 3, '&:hover': { background: 'rgba(255,255,255,0.14)' } },
                scrollbarWidth: 'thin',
                scrollbarColor: 'rgba(255,255,255,0.08) transparent',
            }}>
                {/* Create Form */}
                <Box sx={{ display: "flex", flexDirection: "column", gap: 0, flex: 1 }}>

                    <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
                        {/* Activity Selection */}
                        {packageId && (
                            <Box>
                                <Typography sx={{ fontSize: 11, color: 'rgba(255,255,255,0.35)', textTransform: 'uppercase', fontWeight: 600, letterSpacing: 0.8, mb: 1 }}>
                                    Activities{selectedActivityIds.length > 0 ? ` · ${selectedActivityIds.length}` : ''}
                                </Typography>
                                {activitiesLoading ? (
                                    <CircularProgress size={14} sx={{ color: 'rgba(255,255,255,0.3)' }} />
                                ) : pkgActivities.length === 0 ? (
                                    <Typography sx={{ fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>No activities in this package</Typography>
                                ) : (
                                    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, maxHeight: 160, overflowY: 'auto', '&::-webkit-scrollbar': { width: 4 }, '&::-webkit-scrollbar-track': { background: 'transparent' }, '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 2, '&:hover': { background: 'rgba(255,255,255,0.14)' } }, scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.08) transparent' }}>
                                        {pkgEventDays
                                            .slice()
                                            .sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0))
                                            .map(day => {
                                                const dayActivities = pkgActivities.filter(a => a.package_event_day_id === day._joinId);
                                                if (dayActivities.length === 0) return null;
                                                return (
                                                    <Box key={day._joinId ?? day.id}>
                                                        <Typography sx={{ fontSize: 10, color: 'rgba(255,255,255,0.2)', fontWeight: 600, mb: 0.5, letterSpacing: 0.4 }}>{day.name}</Typography>
                                                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                                                            {dayActivities.map(act => {
                                                                const isSelected = selectedActivityIds.includes(act.id);
                                                                return (
                                                                    <Chip
                                                                        key={act.id}
                                                                        label={act.name}
                                                                        size="small"
                                                                        onClick={() => setSelectedActivityIds(prev =>
                                                                            prev.includes(act.id) ? prev.filter(id => id !== act.id) : [...prev, act.id]
                                                                        )}
                                                                        sx={{
                                                                            cursor: 'pointer',
                                                                            height: 26,
                                                                            fontSize: 12,
                                                                            borderRadius: '6px',
                                                                            bgcolor: isSelected ? 'rgba(123,97,255,0.15)' : 'rgba(255,255,255,0.04)',
                                                                            color: isSelected ? '#a78bfa' : 'rgba(255,255,255,0.5)',
                                                                            border: `1px solid ${isSelected ? 'rgba(123,97,255,0.4)' : 'rgba(255,255,255,0.08)'}`,
                                                                            fontWeight: isSelected ? 500 : 400,
                                                                            '& .MuiChip-label': { px: 1.25 },
                                                                            '&:hover': { bgcolor: isSelected ? 'rgba(123,97,255,0.22)' : 'rgba(255,255,255,0.07)' },
                                                                            transition: 'all 0.15s ease',
                                                                        }}
                                                                    />
                                                                );
                                                            })}
                                                        </Box>
                                                    </Box>
                                                );
                                            })
                                        }
                                    </Box>
                                )}
                            </Box>
                        )}

                        {/* Scene Name */}
                        <Box ref={sceneNameAnchorRef}>
                            <TextField
                                label="Scene Name"
                                placeholder="Type a name or pick from library"
                                value={formData.name}
                                onChange={(e) => handleInputChange("name", e.target.value)}
                                fullWidth
                                required
                                autoFocus
                                InputProps={{
                                    endAdornment: (
                                        <IconButton
                                            size="small"
                                            onClick={() => setLibraryMenuOpen(true)}
                                            sx={{ color: "rgba(255,255,255,0.7)" }}
                                            aria-label="Select from library"
                                        >
                                            <ArrowDropDownIcon />
                                        </IconButton>
                                    ),
                                }}
                                sx={{
                                    "& .MuiOutlinedInput-root": {
                                        color: "white",
                                        "& fieldset": { borderColor: "rgba(255,255,255,0.1)" },
                                        "&:hover fieldset": { borderColor: "rgba(255,255,255,0.2)" },
                                        "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                    },
                                    "& .MuiInputBase-input::placeholder": {
                                        color: "rgba(255,255,255,0.25)",
                                        opacity: 1,
                                    },
                                    "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                }}
                            />
                            {nameAutoGenerated && (
                                <Typography sx={{ fontSize: 11, color: 'rgba(255,255,255,0.25)', mt: 0.5 }}>Auto-generated from activities</Typography>
                            )}
                        </Box>
                        <Menu
                            anchorEl={sceneNameAnchorRef.current}
                            open={libraryMenuOpen}
                            onClose={() => setLibraryMenuOpen(false)}
                            anchorOrigin={{ vertical: "bottom", horizontal: "left" }}
                            transformOrigin={{ vertical: "top", horizontal: "left" }}
                            disableAutoFocusItem
                            PaperProps={{
                                sx: {
                                    bgcolor: "#1a1a1a",
                                    border: "1px solid rgba(255,255,255,0.08)",
                                    maxHeight: 360,
                                    width: sceneNameAnchorRef.current?.clientWidth || 520,
                                    mt: 1,
                                    '&::-webkit-scrollbar': { width: 5 },
                                    '&::-webkit-scrollbar-track': { background: 'transparent' },
                                    '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 3, '&:hover': { background: 'rgba(255,255,255,0.14)' } },
                                    scrollbarWidth: 'thin',
                                    scrollbarColor: 'rgba(255,255,255,0.08) transparent',
                                },
                            }}
                        >
                            {scenes.map((scene) => {
                                const momentsCount = getSceneMomentsCount(scene);
                                const isRealtime = isRealtimeLibraryScene(scene);
                                const durationSeconds = getSceneDurationSeconds(scene);
                                const recordingSetup = scene.recording_setup || null;
                                const cameraCount = recordingSetup?.camera_count ?? 0;
                                const audioCount = recordingSetup?.audio_count ?? 0;
                                const graphicsEnabled = recordingSetup?.graphics_enabled === true;
                                return (
                                    <MenuItem
                                        key={scene.id}
                                        onClick={() => handleSelectLibraryScene(scene)}
                                        sx={{ alignItems: "flex-start", py: 1.25 }}
                                    >
                                        <Box sx={{ display: "flex", flexDirection: "column", gap: 0.75, width: "100%" }}>
                                            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                                                <Box sx={{
                                                    width: 22,
                                                    height: 22,
                                                    borderRadius: 0.75,
                                                    display: "flex",
                                                    alignItems: "center",
                                                    justifyContent: "center",
                                                    bgcolor: isRealtime ? "rgba(76,175,80,0.2)" : "rgba(255,176,32,0.2)",
                                                    color: isRealtime ? "#4CAF50" : "#FFB020",
                                                }}>
                                                    {isRealtime ? <AccessTimeIcon sx={{ fontSize: 14 }} /> : <MovieFilterIcon sx={{ fontSize: 14 }} />}
                                                </Box>
                                                <Typography sx={{ color: "white", fontSize: "0.9rem", fontWeight: 600 }}>
                                                    {scene.name}
                                                </Typography>
                                            </Box>
                                            <Box sx={{ display: "flex", alignItems: "center", gap: 1, flexWrap: "wrap" }}>
                                                <Typography sx={{ color: "rgba(255,255,255,0.65)", fontSize: "0.75rem" }}>
                                                    {formatTime(durationSeconds)}
                                                </Typography>
                                                <Chip
                                                    label={isRealtime ? "Realtime" : "Montage"}
                                                    size="small"
                                                    sx={{
                                                        fontSize: "0.6rem",
                                                        height: 18,
                                                        bgcolor: isRealtime ? "rgba(76,175,80,0.15)" : "rgba(255,176,32,0.15)",
                                                        color: isRealtime ? "#4CAF50" : "#FFB020",
                                                        border: `1px solid ${isRealtime ? "rgba(76,175,80,0.4)" : "rgba(255,176,32,0.4)"}`,
                                                        '& .MuiChip-label': { px: 0.75 },
                                                    }}
                                                />
                                                {momentsCount > 0 && (
                                                    <Chip
                                                        label={isRealtime ? `${momentsCount} Moments` : `${momentsCount} Beats`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(255, 255, 255, 0.15)",
                                                            color: "rgba(255, 255, 255, 0.9)",
                                                            border: "1px solid rgba(255, 255, 255, 0.2)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {cameraCount > 0 && (
                                                    <Chip
                                                        label={`${cameraCount} Cameras`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(76, 175, 80, 0.15)",
                                                            color: "rgba(76, 175, 80, 0.9)",
                                                            border: "1px solid rgba(76, 175, 80, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {audioCount > 0 && (
                                                    <Chip
                                                        label={`${audioCount} Audio`}
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(255, 107, 157, 0.15)",
                                                            color: "rgba(255, 107, 157, 0.9)",
                                                            border: "1px solid rgba(255, 107, 157, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                                {graphicsEnabled && (
                                                    <Chip
                                                        label="Graphics"
                                                        size="small"
                                                        sx={{
                                                            fontSize: "0.6rem",
                                                            height: 18,
                                                            bgcolor: "rgba(0, 229, 255, 0.15)",
                                                            color: "rgba(0, 229, 255, 0.9)",
                                                            border: "1px solid rgba(0, 229, 255, 0.35)",
                                                            '& .MuiChip-label': { px: 0.75 },
                                                        }}
                                                    />
                                                )}
                                            </Box>
                                        </Box>
                                    </MenuItem>
                                );
                            })}
                        </Menu>

                        {/* Scene config row */}
                        <Box sx={{ display: 'flex', gap: 1.5, alignItems: 'flex-start' }}>
                            <FormControl size="small" sx={{ minWidth: 150 }}>
                                <InputLabel sx={{ color: "rgba(255,255,255,0.4)" }}>Type</InputLabel>
                                <Select
                                    value={sceneMode}
                                    onChange={(e) => setSceneMode(e.target.value as "MOMENTS" | "MONTAGE")}
                                    label="Type"
                                    sx={{
                                        color: "white",
                                        "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(255,255,255,0.1)" },
                                        "&:hover .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(255,255,255,0.2)" },
                                        "&.Mui-focused .MuiOutlinedInput-notchedOutline": { borderColor: "#7B61FF" },
                                        "& .MuiSvgIcon-root": { color: "rgba(255,255,255,0.4)" },
                                    }}
                                >
                                    <MenuItem value="MOMENTS">Realtime</MenuItem>
                                    <MenuItem value="MONTAGE">Montage</MenuItem>
                                </Select>
                            </FormControl>
                            <TextField
                                size="small"
                                label="Duration (min)"
                                type="number"
                                value={scheduleDuration}
                                onChange={(e) => setScheduleDuration(e.target.value)}
                                inputProps={{ min: 0 }}
                                InputLabelProps={{ sx: { color: "rgba(255,255,255,0.4)" } }}
                                sx={{ width: 120, input: { color: "white" }, '& fieldset': { borderColor: 'rgba(255,255,255,0.1)' }, '&:hover fieldset': { borderColor: 'rgba(255,255,255,0.2)' } }}
                            />
                            {/* Graphics + Music toggles inline */}
                            {isMomentsScene && (
                                <Box sx={{ display: 'flex', gap: 0.75, alignItems: 'center', ml: 'auto', pt: 0.5 }}>
                                    {[{ label: 'Graphics', value: includeGraphics, set: setIncludeGraphics }, { label: 'Music', value: includeMusic, set: setIncludeMusic }].map(({ label, value, set }) => (
                                        <Chip
                                            key={label}
                                            label={label}
                                            size="small"
                                            onClick={() => set(!value)}
                                            sx={{
                                                cursor: 'pointer',
                                                height: 26,
                                                fontSize: 11,
                                                fontWeight: value ? 500 : 400,
                                                bgcolor: value ? 'rgba(123,97,255,0.15)' : 'transparent',
                                                color: value ? '#a78bfa' : 'rgba(255,255,255,0.3)',
                                                border: `1px solid ${value ? 'rgba(123,97,255,0.35)' : 'rgba(255,255,255,0.08)'}`,
                                                '& .MuiChip-label': { px: 1 },
                                                '&:hover': { bgcolor: value ? 'rgba(123,97,255,0.22)' : 'rgba(255,255,255,0.05)' },
                                                transition: 'all 0.15s ease',
                                            }}
                                        />
                                    ))}
                                </Box>
                            )}
                        </Box>

                        {!isMomentsScene && (
                            <Box sx={{
                                p: 1.5,
                                bgcolor: "rgba(255,255,255,0.02)",
                                borderRadius: 1.5,
                                border: "1px solid rgba(255,255,255,0.06)"
                            }}>
                                <Typography sx={{ color: "rgba(255,255,255,0.5)", fontSize: 12, mb: 1.5, fontWeight: 500 }}>
                                    Beats ({beats.length}){beats.length > 0 ? ` · ${totalBeatsDuration}s` : ''}
                                </Typography>

                                {/* Add Beat Form */}
                                <Box sx={{ display: "flex", gap: 1, mb: 1.5, flexWrap: "wrap" }}>
                                    <TextField
                                        placeholder="Beat name"
                                        value={newBeat.name}
                                        onChange={(e) => setNewBeat({ ...newBeat, name: e.target.value })}
                                        size="small"
                                        sx={{
                                            flex: 1,
                                            minWidth: 160,
                                            "& .MuiOutlinedInput-root": {
                                                color: "white",
                                                "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                            },
                                            "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                        }}
                                    />
                                    <TextField
                                        placeholder="Sec"
                                        type="number"
                                        value={newBeat.duration_seconds}
                                        onChange={(e) => setNewBeat({ ...newBeat, duration_seconds: parseInt(e.target.value) || 1 })}
                                        inputProps={{ min: 1, step: 1 }}
                                        size="small"
                                        sx={{
                                            width: 80,
                                            "& .MuiOutlinedInput-root": {
                                                color: "white",
                                                "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                            },
                                            "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                        }}
                                    />
                                    <TextField
                                        placeholder="Shots"
                                        type="number"
                                        value={newBeat.shot_count}
                                        onChange={(e) => setNewBeat({ ...newBeat, shot_count: Math.max(0, parseInt(e.target.value) || 0) })}
                                        inputProps={{ min: 0, step: 1 }}
                                        size="small"
                                        sx={{
                                            width: 70,
                                            "& .MuiOutlinedInput-root": {
                                                color: "white",
                                                "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                            },
                                            "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                        }}
                                    />
                                    <Button
                                        onClick={handleAddBeat}
                                        size="small"
                                        sx={{
                                            minWidth: 40,
                                            color: "rgba(255,255,255,0.5)",
                                            fontSize: 12,
                                            textTransform: 'none',
                                            '&:hover': { color: '#a78bfa', bgcolor: 'rgba(123,97,255,0.08)' },
                                        }}
                                    >
                                        + Add
                                    </Button>
                                </Box>

                                {/* Beats List */}
                                {beats.length > 0 && (
                                    <List sx={{ maxHeight: 250, overflow: "auto", '&::-webkit-scrollbar': { width: 4 }, '&::-webkit-scrollbar-track': { background: 'transparent' }, '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 2, '&:hover': { background: 'rgba(255,255,255,0.14)' } }, scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.08) transparent' }}>
                                        {beats.map((beat) => (
                                            <ListItem
                                                key={beat.id}
                                                secondaryAction={
                                                    <Box sx={{ display: "flex", gap: 0.5 }}>
                                                        <IconButton
                                                            edge="end"
                                                            onClick={() => setEditingBeatId((beat.id ?? null) === editingBeatId ? null : (beat.id ?? null))}
                                                            size="small"
                                                            title="Edit beat"
                                                        >
                                                            {editingBeatId === beat.id ? (
                                                                <CheckIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.4)" }} />
                                                            ) : (
                                                                <EditIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.2)" }} />
                                                            )}
                                                        </IconButton>
                                                        <IconButton
                                                            edge="end"
                                                            onClick={() => handleRemoveBeat(beat.id)}
                                                            size="small"
                                                        >
                                                            <DeleteIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.15)" }} />
                                                        </IconButton>
                                                    </Box>
                                                }
                                                sx={{
                                                    bgcolor: "rgba(255,255,255,0.03)",
                                                    borderRadius: 1,
                                                    mb: 0.5,
                                                    display: "flex",
                                                    flexDirection: "column",
                                                    alignItems: "flex-start",
                                                }}
                                            >
                                                {editingBeatId === beat.id ? (
                                                    <Box sx={{ display: "flex", gap: 1, width: "100%", pr: 8 }}>
                                                        <TextField
                                                            value={beat.name}
                                                            onChange={(e) => handleUpdateBeat(beat.id, { name: e.target.value })}
                                                            placeholder="Beat name"
                                                            size="small"
                                                            sx={{
                                                                flex: 1,
                                                                "& .MuiOutlinedInput-root": {
                                                                    color: "white",
                                                                    "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                                    "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                                    "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                                                },
                                                            }}
                                                        />
                                                        <TextField
                                                            type="number"
                                                            value={beat.duration_seconds}
                                                            onChange={(e) => handleUpdateBeat(beat.id, { duration_seconds: parseInt(e.target.value) || 1 })}
                                                            inputProps={{ min: 1, step: 1 }}
                                                            size="small"
                                                            sx={{
                                                                width: 80,
                                                                "& .MuiOutlinedInput-root": {
                                                                    color: "white",
                                                                    "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                                    "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                                    "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                                                },
                                                            }}
                                                        />
                                                        <TextField
                                                            type="number"
                                                            value={beat.shot_count}
                                                            onChange={(e) => handleUpdateBeat(beat.id, { shot_count: Math.max(0, parseInt(e.target.value) || 0) })}
                                                            inputProps={{ min: 0, step: 1 }}
                                                            size="small"
                                                            sx={{
                                                                width: 70,
                                                                "& .MuiOutlinedInput-root": {
                                                                    color: "white",
                                                                    "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                                    "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                                    "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                                                },
                                                            }}
                                                        />
                                                    </Box>
                                                ) : (
                                                    <ListItemText
                                                        primary={beat.name}
                                                        secondary={`${beat.duration_seconds}s · ${beat.shot_count} shots`}
                                                        sx={{
                                                            "& .MuiListItemText-primary": { color: "rgba(255,255,255,0.8)", fontSize: 13 },
                                                            "& .MuiListItemText-secondary": { color: "rgba(255,255,255,0.3)", fontSize: 11 },
                                                        }}
                                                    />
                                                )}
                                            </ListItem>
                                        ))}
                                    </List>
                                )}
                            </Box>
                        )}

                        {/* Moments Editor */}
                        {isMomentsScene && (
                            <Box sx={{ 
                                p: 1.5, 
                                bgcolor: "rgba(255,255,255,0.02)", 
                                borderRadius: 1.5,
                                border: "1px solid rgba(255,255,255,0.06)"
                            }}>
                                <Typography sx={{ color: "rgba(255,255,255,0.5)", fontSize: 12, mb: 1.5, fontWeight: 500 }}>
                                    Moments ({moments.length}){moments.length > 0 ? ` · ${totalMomentsDuration}s` : ''}
                                </Typography>

                                {/* Add Moment Form */}
                                <Box sx={{ display: "flex", gap: 1, mb: 1.5 }}>
                                    <TextField
                                        placeholder="Moment name"
                                        value={newMoment.name}
                                        onChange={(e) => setNewMoment({ ...newMoment, name: e.target.value })}
                                        size="small"
                                        sx={{
                                            flex: 1,
                                            "& .MuiOutlinedInput-root": {
                                                color: "white",
                                                "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                            },
                                            "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                        }}
                                    />
                                    <TextField
                                        placeholder="Sec"
                                        type="number"
                                        value={newMoment.duration}
                                        onChange={(e) => setNewMoment({ ...newMoment, duration: parseInt(e.target.value) || 1 })}
                                        inputProps={{ min: 1, step: 1 }}
                                        size="small"
                                        sx={{
                                            width: 80,
                                            "& .MuiOutlinedInput-root": {
                                                color: "white",
                                                "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                            },
                                            "& .MuiInputLabel-root": { color: "rgba(255,255,255,0.4)" },
                                        }}
                                    />
                                    <Button
                                        onClick={handleAddMoment}
                                        size="small"
                                        sx={{
                                            minWidth: 40,
                                            color: "rgba(255,255,255,0.5)",
                                            fontSize: 12,
                                            textTransform: 'none',
                                            '&:hover': { color: '#a78bfa', bgcolor: 'rgba(123,97,255,0.08)' },
                                        }}
                                    >
                                        + Add
                                    </Button>
                                </Box>

                                {/* Moments List */}
                                {moments.length > 0 && (
                                    <List sx={{ maxHeight: 250, overflow: "auto", '&::-webkit-scrollbar': { width: 4 }, '&::-webkit-scrollbar-track': { background: 'transparent' }, '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.08)', borderRadius: 2, '&:hover': { background: 'rgba(255,255,255,0.14)' } }, scrollbarWidth: 'thin', scrollbarColor: 'rgba(255,255,255,0.08) transparent' }}>
                                        {moments.map((moment) => (
                                            <ListItem
                                                key={moment.id}
                                                secondaryAction={
                                                    <Box sx={{ display: "flex", gap: 0.5 }}>
                                                        <IconButton
                                                            edge="end"
                                                            onClick={() => setEditingMomentId((moment.id ?? null) === editingMomentId ? null : (moment.id ?? null))}
                                                            size="small"
                                                            title="Edit moment"
                                                        >
                                                            {editingMomentId === moment.id ? (
                                                                <CheckIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.4)" }} />
                                                            ) : (
                                                                <EditIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.2)" }} />
                                                            )}
                                                        </IconButton>
                                                        <IconButton
                                                            edge="end"
                                                            onClick={() => handleRemoveMoment(moment.id)}
                                                            size="small"
                                                        >
                                                            <DeleteIcon fontSize="small" sx={{ color: "rgba(255,255,255,0.15)" }} />
                                                        </IconButton>
                                                    </Box>
                                                }
                                                sx={{
                                                    bgcolor: "rgba(255,255,255,0.03)",
                                                    borderRadius: 1,
                                                    mb: 0.5,
                                                    display: "flex",
                                                    flexDirection: "column",
                                                    alignItems: "flex-start",
                                                }}
                                            >
                                                {editingMomentId === moment.id ? (
                                                    // Edit Mode
                                                    <Box sx={{ display: "flex", gap: 1, width: "100%", pr: 8 }}>
                                                        <TextField
                                                            value={moment.name}
                                                            onChange={(e) => handleUpdateMoment(moment.id, { name: e.target.value })}
                                                            placeholder="Moment name"
                                                            size="small"
                                                            sx={{
                                                                flex: 1,
                                                                "& .MuiOutlinedInput-root": {
                                                                    color: "white",
                                                                    "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                                    "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                                    "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                                                },
                                                            }}
                                                        />
                                                        <TextField
                                                            type="number"
                                                            value={moment.duration}
                                                            onChange={(e) => handleUpdateMoment(moment.id, { duration: parseInt(e.target.value) || 1 })}
                                                            inputProps={{ min: 1, step: 1 }}
                                                            size="small"
                                                            sx={{
                                                                width: 80,
                                                                "& .MuiOutlinedInput-root": {
                                                                    color: "white",
                                                                    "& fieldset": { borderColor: "rgba(255,255,255,0.08)" },
                                                                    "&:hover fieldset": { borderColor: "rgba(255,255,255,0.15)" },
                                                                    "&.Mui-focused fieldset": { borderColor: "#7B61FF" },
                                                                },
                                                            }}
                                                        />
                                                    </Box>
                                                ) : (
                                                    // View Mode
                                                    <ListItemText
                                                        primary={moment.name}
                                                        secondary={`${moment.duration}s`}
                                                        sx={{
                                                            "& .MuiListItemText-primary": { color: "rgba(255,255,255,0.8)", fontSize: 13 },
                                                            "& .MuiListItemText-secondary": { color: "rgba(255,255,255,0.3)", fontSize: 11 },
                                                        }}
                                                    />
                                                )}
                                            </ListItem>
                                        ))}
                                    </List>
                                )}
                            </Box>
                        )}

                        {/* Error Message */}
                        {error && (
                            <Typography
                                sx={{
                                    color: "#ff6b6b",
                                    fontSize: "0.875rem",
                                    p: 1,
                                    bgcolor: "rgba(255, 107, 107, 0.1)",
                                    borderRadius: 1,
                                }}
                            >
                                {error}
                            </Typography>
                        )}
                    </Box>

                    <Box sx={{ mt: "auto", pt: 2, display: "flex", gap: 1.5, justifyContent: "flex-end", borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                        <Button
                            onClick={onClose}
                            disabled={loading}
                            size="small"
                            sx={{ color: "rgba(255,255,255,0.4)", fontSize: 13 }}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleAddSceneToFilm}
                            disabled={loading}
                            variant="contained"
                            size="small"
                            sx={{
                                bgcolor: "#7B61FF",
                                color: "white",
                                px: 3,
                                fontSize: 13,
                                textTransform: 'none',
                                fontWeight: 500,
                                "&:hover": { bgcolor: "#6b4dd9" },
                                "&:disabled": { bgcolor: "rgba(123,97,255,0.5)" },
                            }}
                        >
                            {loading ? <CircularProgress size={18} /> : "Add Scene"}
                        </Button>
                    </Box>
                </Box>
            </DialogContent>
        </Dialog>
    );
};
export default CreateSceneDialog;
