name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Deploy Frontend to Vercel
        working-directory: ./packages/frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # This makes it available to the shell
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/master" ]; then
            vercel deploy --prod --token $VERCEL_TOKEN --yes
          else
            vercel deploy --token $VERCEL_TOKEN --yes
          fi

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
